# pyocd pipelines

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
- job: functional_test
  displayName: "Functional tests"
  timeoutInMinutes: 200

  # Agent pool.
  pool: functional-test

  # Fully clean workspaces before testing.
  workspace:
    clean: all

  #
  strategy:
    matrix:
      Mac:
        test.os: Darwin
      Linux:
        test.os: Linux
      Win:
        test.os: Windows_NT

  # Run the job only on the agent whose OS matches.
  condition: eq(variables['agent.os'], variables['test.os'])

  steps:
  # Activate venv and install dependencies.
  - script: |
      python3 -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip setuptools wheel
      pip install -r dev-requirements.txt
    displayName: 'Install dependencies'

  # Activate venv and run automated test suite.
  - script: |
      source .venv/bin/activate
      cd test
      python ./automated_test.py --quiet
    displayName: 'Run tests'

  # Publish JUnit-format test results.
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: test/output/*.xml
      testRunTitle: "$(Agent.OS) functional tests"
      platform: "$(Agent.OS)" # Doesn't show up anywhere in Azure UI.
    condition: succeededOrFailed()
    displayName: "Publish test results"

